mir-dataset-loaders/mirdata

README.md
`linspace` has the following prototype
`numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)`
whereas `arange` has the following prototype
`numpy.arange([start, ]stop, [step, ]dtype=None)`
i'm pretty sure that the authors means to use a `step=0.01` and not `num=0.01`
=> linspace -> arange in very_bad_melody_extractor

mirdata/ikala.py, mirdata/utils.py, requirements.txt, tests/test_utils.py
Fixes #52 and #34!
- Replaces the try/catch for imports with a single import for `requests`.  (We would have needed another try/catch for the `HTTPError`, which `requests` gives us for free)
- Creates our own `download_large_file` function to replace `urlretrieve`, which is the one thing requests does _not_ do out of the box.
- Updates `download_from_remote` to throw an HTTPError if things fail, with the discussed friendly error message.
- Updates tests accordingly.
I am not sure if `remote.filename` is the correct thing to format the string with.  @rabitt?  Also cc @drubinstein for review.
=> move to requests, throw friendly exception when downloading a file fails

mirdata/beatles.py, mirdata/ikala.py, mirdata/maps.py, mirdata/medleydb_melody.py, mirdata/medleydb_pitch.py, mirdata/orchset.py, mirdata/salami.py, mirdata/utils.py, tests/test_beatles.py, tests/test_ikala.py, tests/test_medleydb_melody.py, tests/test_medleydb_pitch.py, tests/test_orchset.py, tests/test_salami.py, tests/test_utils.py
Just a suggestion.
Method signatures should be self-explaining if possible. "clobber" is not immediately obvious.
=> Suggestion: rename download argument "clobber" to "force_overwrite"

mirdata/beatles.py, mirdata/ikala.py, mirdata/maps.py, mirdata/medleydb_melody.py, mirdata/medleydb_pitch.py, mirdata/orchset.py, mirdata/salami.py, mirdata/utils.py, tests/test_beatles.py, tests/test_ikala.py, tests/test_medleydb_melody.py, tests/test_medleydb_pitch.py, tests/test_orchset.py, tests/test_salami.py, tests/test_utils.py
* Makes all dataset track objects classes instead of namedtuples (Closes #69 )
* removes the dataset name from global variables (e.g. `orchset.ORCHSET_METADATA` --> `orchset.METADATA`
* Multiplies the mono ikala audio files by 2 (Fixes #63 )
* Offsets ikala timestamps to be center aligned (unreported bug)
* Simplifies the API for `salami._load_sections` - @magdalenafuentes can you take a look and make sure what I did makes sense?
* Moves the `EnvironmentError` exception that was getting called in `load_track` to `_load_metadata`.
=> moved all namedtuple track objects to classes

mirdata/dali.py, setup.py
#145 
In order to install DALI, you now install by running 
`pip install mirdata[dali]`. It will not be installed by default.
@rabitt @magdalenafuentes where should I document this behavior since it's probably nontrivial for most people to know.
=> 145 - Dali is now optional

CONTRIBUTING.md, mirdata/beatles.py, mirdata/dali.py, mirdata/gtzan_genre.py, mirdata/guitarset.py, mirdata/ikala.py, mirdata/medley_solos_db.py, mirdata/medleydb_melody.py, mirdata/medleydb_pitch.py, mirdata/orchset.py, mirdata/rwc_classical.py, mirdata/rwc_jazz.py, mirdata/rwc_popular.py, mirdata/salami.py, mirdata/tinysol.py
Fixes #191 
I removed the documentation for global variables, because they shouldn't be used nor modified by the user anyway.
I added more details, especially on RWC, DALI, and SALAMI.
=> update loader docstrings

mirdata/dali.py, setup.py, tests/test_loaders.py
closes #229 bug
closes #197 `NotImplementedError`
many thanks to @gabolsgabs for this update
triaged for v0.2
TODO:
=> bugfix dali.download(), implement dali.Track.to_jams()

.gitignore, CONTRIBUTING.md, tests/conftest.py, tests/test_full_dataset.py, tests/test_loaders.py, tests/test_utils.py
fixes #234
What changed:
* I've added `tests/test_full_dataset.py`, which downloads, validates and loads a dataset, and for each track object, calls all properties to make sure they are callable.
* we can now run pytest with an optional `--local` argument (in `tests/conftest.py`) which skips any tests that are built for the remote tests and always fail
* I've decorated a few of the existing tests to either skip when run remotely or skip when run locally, when it makes sense
* Updated documentation in `CONTRIBUTING.md` to explain how to use the `--local` flag and how to run the new full test.
Once this is merged, we should (ugh...) run this for every dataset and make sure there are no secret outstanding bugs.
=> Add local exhaustive dataset tests

CONTRIBUTING.md, mirdata/beatles.py, mirdata/dali.py, mirdata/ikala.py, mirdata/jams_utils.py, mirdata/medley_solos_db.py, mirdata/medleydb_melody.py, mirdata/medleydb_pitch.py, mirdata/orchset.py, mirdata/rwc_classical.py, mirdata/rwc_jazz.py, mirdata/rwc_popular.py, mirdata/salami.py, mirdata/tinysol.py, tests/test_jams_utils.py, tests/test_loaders.py
Fixes #226
What changed:
* the jams_converter now takes `audio_path` as an argument which is used to fill the duration value of the resulting jams object
* this removes the need for computing duration in the individual `to_jams()` methods
* we can catch the OSError within the `jams_converter` function itself
* updated tests
* updated contributing
=> fixes #226

setup.py, tests/test_beatles.py, tests/test_loaders.py
Adds descriptive messges to asserts in `test_loaders.py`. I started writing them for the individual datasets (in test_beatles) but stopped as it's less useful
=> fixes #246

mirdata/track.py, mirdata/version.py, tests/test_track.py
Reverts mir-dataset-loaders/mirdata#295
=> Revert "MultiTrack class"

mirdata/datasets/indexes/tinysol_index.json, mirdata/datasets/tinysol.py, scripts/make_tinysol_index.py
Modify `tinysol` index and module to be compatible with `Dataset` and in the same format as other datasets. Fixes #351
=> Fix tinysol localpath

mirdata/core.py
reintroduces `Dataset.readme`, but instead of printing text, prints a link to the relevant docs.
This along with #407 (removes hidden `dataset_info` from Dataset docstring), closes #410
=> Dataset.readme

docs/source/tutorial.rst, mirdata/annotations.py, mirdata/datasets/guitarset.py, mirdata/datasets/saraga_carnatic.py, mirdata/datasets/saraga_hindustani.py, tests/test_annotations.py, tests/test_guitarset.py
Closes #405 
* Changes the validators in `annotations.py` to not accept `None` as input variables unless the input is optional
* Updates existing loader (guitarset) which was not following missing -> None convention
* some small doc formatting adjustments
=> Force missing annotations to be None

mirdata/core.py
Right now the Dataset object docstring has a formatting mistake, related to the multiline comment and the docstring_inherit decorator not handling it properly - the second line is treated as a new variable ("returns")
This PR doesn't fix it, but puts a bandaid on the problem by making all the arguments have one-line descriptions.
=> track docstring in dataset is incorrectly formatted

README.md, docs/conf.py, docs/index.rst, docs/source/contributing.rst, docs/source/faq.rst, docs/source/mirdata.rst, docs/source/overview.rst, docs/source/quick_reference.rst, docs/source/tutorial.rst, mirdata/core.py, scripts/legacy/update_index.py
We included links to the "latest" version of the docs which points to master. This changes it to point to stable, and removes links when they weren't needed (e.g. internal docs references).
+ adds version information to medley-solos-db, which was missing
=> Update links to documentation

docs/source/contributing.rst
Genis and I have had the same problem in the last days. Black command in contributing is not the correct one.
new command on contributing page:
```bash
black --target-version py36 --target-version py37 --target-version py38 --skip-string-normalization mirdata/ tests/
```
=> fix black command

.readthedocs.yaml, docs/source/contributing.rst
Warnings in the docs build fail silently, and result in parts of the docs not rendering (e.g. the table of supported datasets). This should switch it, so that docs warnings cause an error in the build, and will show up in our test integrations
=> add readthedocs config file

docs/source/table.rst
A one-liner indicating that, unfortunately, the Billboard audio is not available on request. I reached out to Ashley Burgoyne (the dataset's creator) who informed me that the audio could not be shared. CC @Spijkervet who originally added the dataset to this library, on the off chance that there is some other path for obtaining the audio.
=> Billboard audio is not available on request

mirdata/annotations.py, mirdata/datasets/guitarset.py, tests/datasets/test_guitarset.py, tests/test_annotations.py
Part of #502  -
* adds `to_mir_eval` methods to NoteData, MultiF0Data, and F0Data
Adds two new cached properties to Guitarset:
* `Track.notes_all` (a combination of `Track.notes` across all strings)
* `Track.multif0` (a combination of `Track.pitch_contours` across all strings)
=> Add to_mir_eval for NoteData, MultiF0Data, and F0Data

setup.py
The latest builds are all failing because music21 updated in an incompatible way and we hand't pinned the version. This pins it!
=> pin music 21 version

setup.py
Fixes #601 
Add missing comma to `setup.py` to be able to `pip install .`
=> Fix setup extras_requirements installation. Add missing comma.

docs/source/contributing.rst, docs/source/overview.rst, docs/source/quick_reference.rst, docs/source/tutorial.rst
i was reading the documentation to create a loader and i found some typos, so i just ran a spell-check in the `docs` folder and fixed them.
* spell-check documentation files and fix typos
* `contributing.rst`:
- fix pip install syntax to install optional dependencies (#564)
- remove `--black` flag from pytest command because it was not working
=> minor fixes: documentation

mirdata/datasets/compmusic_carnatic_rhythm.py
Just spotted a wrong link for the index remotes in the Carnatic Music Rhythm dataset. This PR fixes it. 
That is the misspelling: hhttps --> https
=> Fix wrong Carnatic Music Rhythm Zenodo link

.github/workflows/ci.yml, .github/workflows/formatting.yml, .github/workflows/lint-python.yml, mirdata/annotations.py, mirdata/core.py, mirdata/datasets/acousticbrainz_genre.py, mirdata/datasets/ballroom.py, mirdata/datasets/candombe.py, mirdata/datasets/cipi.py, mirdata/datasets/compmusic_carnatic_rhythm.py, mirdata/datasets/compmusic_carnatic_varnam.py, mirdata/datasets/compmusic_hindustani_rhythm.py, mirdata/datasets/compmusic_indian_tonic.py, mirdata/datasets/compmusic_raga.py, mirdata/datasets/cuidado.py, mirdata/datasets/da_tacos.py, mirdata/datasets/egfxset.py, mirdata/datasets/filosax.py, mirdata/datasets/four_way_tabla.py, mirdata/datasets/hainsworth.py, mirdata/datasets/idmt_smt_audio_effects.py, mirdata/datasets/saraga_carnatic.py, mirdata/datasets/saraga_hindustani.py, mirdata/datasets/simac.py, mirdata/datasets/slakh.py, mirdata/download_utils.py, mirdata/io.py, mirdata/jams_utils.py, tests/datasets/test_candombe.py
Updated CI, linting and formatting in github actions workflow.
actions/checkout@v3 --> actions/checkout@v4
actions/cache@v3 --> uses: actions/cache@v4
conda-incubator/setup-miniconda@v2 --> uses: conda-incubator/setup-miniconda@v3
- formatted with black 25.1
=> Updated github actions workflows

mirdata/datasets/cipi.py, mirdata/datasets/compmusic_carnatic_varnam.py, mirdata/datasets/dali.py, mirdata/datasets/guitarset.py, mirdata/datasets/tonas.py, mirdata/io.py
As discussed with @genisplaja in https://github.com/mir-dataset-loaders/mirdata/pull/652#pullrequestreview-2735847747, this PR makes an initial attempt to allow for the use of optional `args` and `kwargs` in the two decorator functions inside `io`.
The changes to the decorators themselves are very minor. I also changed a few functions in several loaders that weren't previously using the decorators. These are the same as defined in `test_loaders.EXCEPTIONS`, i.e.:
```
EXCEPTIONS = {
"dali": {"load_annotations_granularity": {"granularity": "notes"}},
"guitarset": {
"load_pitch_contour": {"string_num": 1},
"load_notes": {"string_num": 1},
"load_chords": {"leadsheet_version": False},
},
"tonas": {"load_f0": {"corrected": True}},
"compmusic_carnatic_varnam": {
"load_notation": {
"taala_path": …
```
=> Add support for `*args` and `**kwargs` in `io.coerce_to_*` decorators

mirdata/datasets/mtg_jamendo_autotagging_moodtheme.py, tests/datasets/test_mtg_jamendo_autotagging_moodtheme.py
Fixes #668 
- Refactor the tags method to return a list of tags such as `['dramatic', 'epic', 'inspiring', 'powerful', 'upbeat', 'uplifting']` instead of a string such as `"mood/theme---dramatic"`
- Modify metadata loading to accommodate multiple tags. Previously the tags method only returned the first tag out of many.
- Update the tests to reflect the change in the expected tags data type from string to list.
=> Fixes #668 - Refactor tags handling and update tests for Jamendo

docs/source/tutorial.rst
This pull request makes a small documentation update to the `docs/source/tutorial.rst` file. 
Previously, all the subsections were under the "Installation" subsection rather than their own separate subsections.
It has now been fixed to have separate subsections as expected.
=> Fix Documentation - Separate the subsections in the Tutorial

.github/workflows/ci.yml, .github/workflows/formatting.yml, .github/workflows/lint-python.yml, .github/workflows/pythonpublish.yml
All GitHub Actions workflows now support manual triggering through the `workflow_dispatch` event, which adds a "Run Workflow" button to each workflow for more convenience.
=> Add manual trigger to all GitHub Actions workflows

mirdata/datasets/guitarset.py, mirdata/download_utils.py, mirdata/validate.py
Fixes #679 
**Problem:**
When using mirdata in Google Colab notebooks, download progress messages and download instructions are not displayed in the cell output. This happens because:
1. Google Colab's root logger is configured to WARNING level by default
2. mirdata's download messages are logged at INFO level (see download_utils.py line 18: `logging.basicConfig(format="%(levelname)s: %(message)s", level=logging.INFO)`)
3. The actual download progress messages use `logging.warning()` but the download instructions (`DOWNLOAD_INFO`) use the INFO level through `info_message` parameter
**Current Behavior:**
In Google Colab, users don't see:
- Download instructions that explain how to manually download datasets
- Progress information about what's being downloaded
**Expected Behavior:**
Users …
=> Fix Download Instructions not displaying in Google Colab 

mirdata/download_utils.py, tests/test_download_utils.py
Fixes #570 - UnicodeDecodeError when using datasets with zipped index files (e.g., AcousticBrainz Genre dataset).
The `download_utils` module could handle zipped dataset files but not zipped index files. When an index file was downloaded as `.json.zip` but the metadata specified the filename as `.json`, the system would try to read the zip file directly as JSON, causing `UnicodeDecodeError`.
Additionally, there was a bug where index files would be downloaded twice when explicitly requested in `partial_download`.
1. **Zipped Index Handling**: Added automatic detection and extraction of zipped index files
- After downloading any file via `download_from_remote`, check if it's a zip file using magic bytes (`b'PK'`)
- If it's a zip file, automatically extract it using the existing `unzip` …
=> Add support for zipped index files
