mir-dataset-loaders/mirdata

- README.md
- mir_dataset_loaders/__init__.py
- mir_dataset_loaders/download_utils.py
- mir_dataset_loaders/ikala.py
- mir_dataset_loaders/indexes/ikala_index.json
- mir_dataset_loaders/indexes/medleydb_pitch_index.json
- mir_dataset_loaders/indexes/orchset_index.json
- mir_dataset_loaders/load_utils.py
- mir_dataset_loaders/medleydb_pitch.py
- mir_dataset_loaders/orchset.py
- scripts/make_ikala_index.py
- scripts/make_medleydb_pitch_index.py
- scripts/make_orchset_index.py
* index only contains file information, no metadata
* index has checksums for all files
* moved all metadata parsing to loaders
* add loader for medleydb-pitch
* update docs with hopefully up to date usage
> Refactor index

- mir_dataset_loaders/ikala.py
* add helper functions to load the vocals, instrumentals, and mix from ikala split mono audio files.
* add download instructions
> Ikala audio helpers

- mir_dataset_loaders/ikala.py
- mir_dataset_loaders/medleydb_pitch.py
- mir_dataset_loaders/orchset.py
* add cite data to `ikala`
* make `medleydb_pitch.load_pitch` a hidden function
* in `orchset` and `medleydb_pitch`, load `None` if file doesn't exist
> Misc debug

- mir_dataset_loaders/utils.py
For #23 
I added a logging function that takes an optional silence flag. It may be better to instead use the python `logging` module and let the user set the level.
> Add silence flag to validation

- mir_dataset_loaders/__init__.py
- mir_dataset_loaders/indexes/medleydb_melody_index.json
- mir_dataset_loaders/medleydb_melody.py
- mir_dataset_loaders/medleydb_pitch.py
- scripts/make_medleydb_melody_index.py
> Medleydb melody

- mirdata/__init__.py
- setup.py
These weren't exposed in __init__.py causing me troubles. exposing them here.
> expose beatles and salami

- README.md
remove `mdl` from examples, fix broken links
> Fix dataset name in README

- mirdata/salami.py
Fix bugs in load_track when data_home is None, and get audio path from salami index properly
> Salami bug

- mirdata/beatles.py
- mirdata/medleydb_melody.py
- mirdata/medleydb_pitch.py
- mirdata/orchset.py
- mirdata/salami.py
Solves #57.
Tested using the code segment from #57
> properly use validate

- mirdata/salami.py
- requirements.txt
- tests/test_salami.py
Working on it! 
Will eventually contribute to #54, pushing for reference.
⛵️ 🚜 🚋
> Add tests for Salami

- tests/test_beatles.py
Another few tests for #54!  🚗 ⛵️ 🚢
> Add tests to Beatles dataloaders

- mirdata/beatles.py
- mirdata/ikala.py
- mirdata/maps.py
- mirdata/medleydb_melody.py
- mirdata/medleydb_pitch.py
- mirdata/orchset.py
- mirdata/salami.py
- mirdata/utils.py
- scripts/make_beatles_index.py
- scripts/make_ikala_index.py
- scripts/make_medleydb_melody_index.py
- scripts/make_medleydb_pitch_index.py
- scripts/make_orchset_index.py
- scripts/make_salami_index.py
- tests/test_beatles.py
- tests/test_download.py
- tests/test_orchset.py
- tests/test_salami.py
- tests/test_utils.py
> standardize on single quotes except in triple quotes

- .gitignore
- docs/Makefile
- docs/conf.py
- docs/index.rst
- docs/make.bat
- mirdata/beatles.py
- mirdata/ikala.py
- mirdata/medleydb_melody.py
- mirdata/medleydb_pitch.py
- mirdata/orchset.py
- mirdata/salami.py
- mirdata/utils.py
- mirdata/version.py
* need to configure `index.rst` etc better but it kinda works
* following google docstring format
> Docs - first attempt

- README.md
> "data is" -> "data are" in README.md

- README.md
- docs/.readthedocs.yml
- docs/conf.py
- docs/requirements.txt
- docs/source/mirdata.rst
- setup.py
* fix failing read the docs build
* add rtd badge
> Fix failing rtd build

- mirdata/beatles.py
- mirdata/ikala.py
- mirdata/medleydb_melody.py
- mirdata/medleydb_pitch.py
- mirdata/orchset.py
- mirdata/salami.py
- setup.py
- tests/test_beatles.py
- tests/test_ikala.py
- tests/test_medleydb_melody.py
- tests/test_medleydb_pitch.py
- tests/test_orchset.py
- tests/test_salami.py
Hello @rabitt, it was easier to cut a new branch than update the old one - let me know what you think!
> Add __repr__ to existing datasets

- tests/test_beatles.py
- tests/test_download_utils.py
- tests/test_orchset.py
- tests/test_salami.py
@rabitt Here are some tests for you. Merge into your branch when you want to.
> Common downloader tests

- mirdata/ikala.py
- mirdata/medleydb_melody.py
- mirdata/medleydb_pitch.py
- mirdata/orchset.py
- mirdata/rwc_classical.py
- mirdata/rwc_genre.py
- mirdata/rwc_jazz.py
- mirdata/rwc_popular.py
- mirdata/salami.py
- setup.py
> replace print with logging.info

- mirdata/download_utils.py
- setup.py
> make all subdirectories

- mirdata/beatles.py
- mirdata/download_utils.py
- mirdata/rwc_classical.py
- mirdata/salami.py
- setup.py
- Fixes  #116 
- Simplifies tar.gz download
- RWC beat positions to int
> Checksum and minor fixes

- mirdata/download_utils.py
> Move back from requests to urllib

- CONTRIBUTING.md
- docs/source/mirdata.rst
- mirdata/beatles.py
- mirdata/guitarset.py
- mirdata/ikala.py
- mirdata/medley_solos_db.py
- mirdata/medleydb_melody.py
- mirdata/medleydb_pitch.py
- mirdata/orchset.py
- mirdata/rwc_classical.py
- mirdata/rwc_genre.py
- mirdata/rwc_jazz.py
- mirdata/rwc_popular.py
- mirdata/salami.py
- mirdata/utils.py
- setup.py
Initial idea for how to fix #100 .
WIP, will extend to all loaders if this is the way we decide to go.
> Speed up import mirdata

- mirdata/beatles.py
- mirdata/medleydb_melody.py
> Fix tar checksums

- .circleci/config.yml
- setup.py
- tests/test_salami.py
> 146 - Uncomment audio loader asserts in salami

- mirdata/utils.py
- setup.py
- tests/test_utils.py
> document validator + print message in case of success

- mirdata/medleydb_melody.py
- mirdata/utils.py
- tests/test_medleydb_melody.py
* Fixes #101 by adding a new data type called `utils.MultipitchData` which is compatible with mir_eval's multipitch.evaluate function.
* Updates `medleydb_melody` to load melody3 data as MultipitchData
> [MRG] Add MultipitchData

- mirdata/download_utils.py
- mirdata/tinysol.py
- setup.py
> remove six from requirements + remove unused imports

- docs/requirements.txt
- docs/source/mirdata.rst
- mirdata/tinysol.py
- setup.py
Fixes #192 
@rabitt can you do `pip install -e .[docs]` on a fresh environment and tell me if this works on your machine?
> Fix docs for v0.2, add sndfile

- mirdata/dali.py
- mirdata/guitarset.py
- mirdata/jams_utils.py
- mirdata/utils.py
- tests/test_dali.py
- tests/test_guitarset.py
- tests/test_jams_utils.py
Addresses #161 
[EDIT by @lostanlen: closes #161]
> Updating NoteData type to be compatible with mir_eval trancription

- CONTRIBUTING.md
- docs/source/mirdata.rst
- mirdata/beatles.py
- mirdata/dali.py
- mirdata/gtzan_genre.py
- mirdata/guitarset.py
- mirdata/ikala.py
- mirdata/medley_solos_db.py
- mirdata/medleydb_melody.py
- mirdata/medleydb_pitch.py
- mirdata/orchset.py
- mirdata/rwc_classical.py
- mirdata/rwc_jazz.py
- mirdata/rwc_popular.py
- mirdata/salami.py
- mirdata/tinysol.py
- scripts/print_track_docstring.py
Updating docstrings to behave better with sphinx
> Docs beautification

- mirdata/gtzan_genre.py
- tests/test_gtzan_genre.py
> Fix gtzan_genre hip-hop tag

- tests/test_loaders.py
fix for https://github.com/mir-dataset-loaders/mirdata/issues/273
> fix for issue 273

- .circleci/config.yml
- README.md
Updates the top level readme
- removes gif which has out of date code (closes #279)
- adds a short example at the top of the README
- cleans up a few minor details throughout the readme
> Fixes #279

- mirdata/version.py
- setup.py
bump librosa version and remove numba patch
> bump librosa version

- CONTRIBUTING.md
class MultiTrack(track.MultiTrack): 
class MultiTrack(core.MultiTrack):
> corrected track->core

- mirdata/utils.py
- tests/indexes/acousticbrainz_genre_dataset_little_test.json
- tests/test_utils.py
> Remote index

- mirdata/datasets/rwc_classical.py
- mirdata/datasets/rwc_jazz.py
- mirdata/datasets/rwc_popular.py
- mirdata/version.py
- tests/test_rwc_classical.py
> Fix RWC metadata

- README.md
This implements #245 in a collaborative way.
@rabitt and I are restructuring the docs, trying to make attributes and functions of loaders collapse, and writing the text on the **mirdata** section of the docs.
@PRamoneda and @genisplaja if that's ok you could start drafting **Getting started** and once we have the structure in place you add PRs to this PR with your parts? Besides, as we went through the other day, we noticed that the docs of some current loaders need some fix (e.g. [AcousticBrainz genre JSON example](https://mirdata.readthedocs.io/en/latest/source/mirdata.html#ab-genre), or [cante100 is missing the docs entirely](https://mirdata.readthedocs.io/en/latest/source/mirdata.html#cante100), same for mridangam_stroke and tonality_classicaldb.
An initial idea to start discussion: …
> Documentation audit

- mirdata/datasets/acousticbrainz_genre.py
> Add bibtex Acousticbrainz

- docs/source/contributing.rst
- docs/source/overview.rst
Adds some more details to contributing about conventions.
> Contributing conventions docs

- docs/conf.py
- docs/requirements.txt
- docs/source/contributing.rst
- mirdata/datasets/beatles.py
- mirdata/datasets/cante100.py
- mirdata/datasets/dali.py
- mirdata/datasets/giantsteps_key.py
- mirdata/datasets/giantsteps_tempo.py
- mirdata/datasets/groove_midi.py
- mirdata/datasets/gtzan_genre.py
- mirdata/datasets/guitarset.py
- mirdata/datasets/ikala.py
- mirdata/datasets/irmas.py
- mirdata/datasets/maestro.py
- mirdata/datasets/medley_solos_db.py
- mirdata/datasets/medleydb_melody.py
- mirdata/datasets/medleydb_pitch.py
- mirdata/datasets/mridangam_stroke.py
- mirdata/datasets/orchset.py
- mirdata/datasets/rwc_classical.py
- mirdata/datasets/rwc_jazz.py
- mirdata/datasets/rwc_popular.py
- mirdata/datasets/salami.py
- mirdata/datasets/tinysol.py
- mirdata/datasets/tonality_classicaldb.py
- mirdata/io.py
- mirdata/validate.py
- setup.py
- tests/test_io.py
- tests/test_loaders.py
A work in progress example of:
- Using file-like interfaces instead of passing paths around to the underlying loaders
- Adding type information along the way.
> string to structure

- .circleci/config.yml
- mirdata/datasets/beatport_key.py
- mirdata/datasets/ikala.py
- mirdata/io.py
- mirdata/validate.py
- setup.py
- tests/conftest.py
- tests/test_annotations.py
- tests/test_cante100.py
- tests/test_download_utils.py
- tests/test_ikala.py
- tests/test_irmas.py
- tests/test_jams_utils.py
- tests/test_loaders.py
- tests/test_rwc_classical.py
- tests/test_saraga_carnatic.py
- tests/test_saraga_hindustani.py
- tests/test_tonality_classicaldb.py
- tox.ini
This PR handles a few bits related to formatting:
1. python3.8 is now tested for and is used as the basepython for black
2. tox has been refactored to include a `check-formatting` and `format` env
3. `check-formatting` has been added to circleci
> formatting

- docs/source/tutorial.rst
removed Track.title from orchset in Tutorial
> removed Track.title in Tutorial

- .circleci/config.yml
- mirdata/core.py
- mirdata/datasets/tonality_classicaldb.py
- tox.ini
This PR adds a mypy check but not strict meaning that it only checks what has already been added. I fixed up some typing along the way.
> Add mypy (not strict)

- docs/source/contributing.rst
- docs/source/tutorial.rst
> Move development info to contributing

- mirdata/annotations.py
- tests/test_annotations.py
Adds `NoteData.to_multif0`, which converts a `NoteData` annotation into a `MultiF0Data` annotation.
Part of #504
> add note to multif0 converter
